import 'package:equatable/equatable.dart';

/// A user action event published to the AI copilot.
class CopilotEvent {
  const CopilotEvent({
    required this.eventType,
    required this.payload,
    this.timestamp,
  });

  final String eventType;
  final Map<String, dynamic> payload;
  final DateTime? timestamp;

  Map<String, dynamic> toJson() => {
        'event_type': eventType,
        'payload': payload,
        'timestamp': (timestamp ?? DateTime.now()).toIso8601String(),
      };
}

/// AI-generated recommendation surfaced to the user.
class Recommendation extends Equatable {
  const Recommendation({
    required this.id,
    required this.type,
    required this.title,
    this.description,
    this.score,
    this.reason,
    this.actionUrl,
    this.metadata = const {},
  });

  final String id;
  final String type; // "course", "job", "action"
  final String title;
  final String? description;
  final double? score;
  final String? reason;
  final String? actionUrl;
  final Map<String, dynamic> metadata;

  @override
  List<Object?> get props => [id, type];

  factory Recommendation.fromJson(Map<String, dynamic> json) {
    return Recommendation(
      id: '${json['id'] ?? ''}',
      type: json['type'] as String? ?? 'unknown',
      title: json['title'] as String? ?? '',
      description: json['description'] as String?,
      score: (json['score'] as num?)?.toDouble(),
      reason: json['reason'] as String?,
      actionUrl: json['action_url'] as String?,
      metadata: json['metadata'] as Map<String, dynamic>? ?? {},
    );
  }
}

/// Contextual data returned by /ai-copilot/context.
class CopilotContext {
  const CopilotContext({
    this.userId,
    this.leadScore,
    this.nextAction,
    this.summary,
    this.metadata = const {},
  });

  final String? userId;
  final double? leadScore;
  final String? nextAction;
  final String? summary;
  final Map<String, dynamic> metadata;

  factory CopilotContext.fromJson(Map<String, dynamic> json) {
    return CopilotContext(
      userId: json['user_id'] as String?,
      leadScore: (json['lead_score'] as num?)?.toDouble(),
      nextAction: json['next_action'] as String?,
      summary: json['summary'] as String?,
      metadata: json['metadata'] as Map<String, dynamic>? ?? {},
    );
  }
}

/// Email draft generated by /ai-copilot/email-draft.
class EmailDraft {
  const EmailDraft({
    required this.subject,
    required this.body,
    this.to,
  });

  final String subject;
  final String body;
  final String? to;

  factory EmailDraft.fromJson(Map<String, dynamic> json) {
    return EmailDraft(
      subject: json['subject'] as String? ?? '',
      body: json['body'] as String? ?? '',
      to: json['to'] as String?,
    );
  }
}
